// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALPxrPlSCWxLr7CbvagZW0CSUiKaTKfeQ',
    appId: '1:698885539759:web:7a6e060d9d160fe54c515a',
    messagingSenderId: '698885539759',
    projectId: 'flutterfb-8cf28',
    authDomain: 'flutterfb-8cf28.firebaseapp.com',
    storageBucket: 'flutterfb-8cf28.firebasestorage.app',
    measurementId: 'G-NME6LD6MXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8lzwqUe-GRhhUSByvpz9GyN1M9JA_UQY',
    appId: '1:698885539759:android:0a50de092258cfb74c515a',
    messagingSenderId: '698885539759',
    projectId: 'flutterfb-8cf28',
    storageBucket: 'flutterfb-8cf28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGcgonyc0towSgCHaWl0IlUNZgWDbC7VQ',
    appId: '1:698885539759:ios:2fe737a5885d8efd4c515a',
    messagingSenderId: '698885539759',
    projectId: 'flutterfb-8cf28',
    storageBucket: 'flutterfb-8cf28.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGcgonyc0towSgCHaWl0IlUNZgWDbC7VQ',
    appId: '1:698885539759:ios:2fe737a5885d8efd4c515a',
    messagingSenderId: '698885539759',
    projectId: 'flutterfb-8cf28',
    storageBucket: 'flutterfb-8cf28.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALPxrPlSCWxLr7CbvagZW0CSUiKaTKfeQ',
    appId: '1:698885539759:web:92b5915fd514c19d4c515a',
    messagingSenderId: '698885539759',
    projectId: 'flutterfb-8cf28',
    authDomain: 'flutterfb-8cf28.firebaseapp.com',
    storageBucket: 'flutterfb-8cf28.firebasestorage.app',
    measurementId: 'G-6X1BP6Z3TZ',
  );

}